### PR TITLE
Add producer

### PR DESCRIPTION
**Pull request by brandynbennett**
Create a `Polyn.Producer` module with a single `pub` function that will validate and publish events following Polyn conventions

### CODE REVIEW

**Comment by mmmries** [comment]
Hey @brandynbennett I just started reviewing this and haven't gotten all the way through, but I was curious about the decision to turn this into a library with its own supervision tree, vs leaving it as a library only?

My default for libraries is usually to provide the functions that enforce conventions and behavior, but leave it up to the application code to decide things like the startup procedure and identifying which connection to use when publishing etc. I'm curious if you default the other direction towards having libraries start and manage their own state, or maybe there are some requirements here that pushed us in the direction of handling the delivery at runtime?

I don't have a strong pushback here, just looking to get more informed about our design goals as I try to review the code.

**Comment by brandynbennett** [comment]
@mmmries Thanks for bringing this up. Your question helped me think about this some more. Initially my desire was to simplify the setup process and minimize the number of arguments to pass to a function. However after thinking about this more I think that leaving the connection setup to the application code would be wiser so that it isn't prevented from making its own decisions about how connections will be handled. I'll do some refactoring and remove the connection setup from the library so that the application code can have control of that.

**Comment by brandynbennett** [comment]
I'm also wondering about if something like the Ecto Repo is a pattern that could be used here. In Ecto you create a Repo module that handles all of your connection and pooling for you. So rather than having to pass a `conn` argument to every function you just run everything through the `Repo` module. This would be a larger design change that would probably need to be considered at the `Gnat` level though.

**Comment by brandynbennett** [comment]
@mmmries I made that refactor, passing in an explicit connection is required now

**Review by fugufish — APPROVED** [review]

**Pull request merged**
